//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huellitas.Empleadosws.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public System.Guid idcita { get; set; }
        public System.DateTime fecha { get; set; }
        public int idhoracita { get; set; }
        public System.Guid idcliente { get; set; }
        public System.Guid idservicio { get; set; }
        public int idestadocita { get; set; }
    }
}
