//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huellitas.Empleadosws.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public System.Guid id { get; set; }
        public string apellidoP { get; set; }
        public string apellidoM { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string nombrec { get; set; }
    }
}
